name: langfuse-template-space
type: gradio-space
sdk: docker

metadata:
  space_id: Chris4K/langfuse-template-space
  original_url: https://huggingface.co/spaces/Chris4K/langfuse-template-space

deploy:
  targets:
    - public-repo
    - huggingface

build:
  command: bash build.sh

test:
  command: echo "Tests not yet implemented"
